const images = {
  logo: require('../Assets/Images/riderlogo.png'),
  username: require('../Assets/Images/username.png'),
  password: require('../Assets/Images/password.png'),
  friday: require('../Assets/Images/friday.png'),
  deliveries: require('../Assets/Images/deliveries.png'),
  stats: require('../Assets/Images/stats.png'),
  help: require('../Assets/Images/help.png'),
  settings: require('../Assets/Images/settings.png'),
  logout: require('../Assets/Images/logout.png'),
  gps: require('../Assets/Images/gps.png'),
  backarrow: require('../Assets/Images/backarrow.png'),
  bellicon: require('../Assets/Images/bellicon.png'),
  hamburger: require('../Assets/Images/hamburger.png'),
  changepassword: require('../Assets/Images/changepassword.png'),
  helptube: require('../Assets/Images/helptube.png'),
  colleagues: require('../Assets/Images/colleagues.png'),
  payments: require('../Assets/Images/payments.png'),
  rightarrow: require('../Assets/Images/rightarrow.png'),
  stats: require('../Assets/Images/stats.png'),
  telephone: require('../Assets/Images/telephone.png'),
  acceptedorders: require('../Assets/Images/acceptedorders.png'),
  pendingorders: require('../Assets/Images/pendingorders.png'),
  rejectedorders: require('../Assets/Images/rejectedorders.png'),
  graph: require('../Assets/Images/graph.png'),
};
export default images;
